In [1]:
import numpy as np
import pygame
import sys
import math

pygame 2.0.0 (SDL 2.0.12, python 3.7.6)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [39]:
Blue=(0,0,255)
Black=(0,0,0)
Red=(255,0,0)
Green=(0,128,0)


In [40]:
import pygame 
#fonts=pygame.font.SysFont("arial",50)
fonts=pygame.font.Font("C:\Windows\Fonts\Arial.ttf",50)

In [41]:
def create_board():
	board = np.zeros((Rows,Cols))
	return board
# A matrix of zeroes

#initializing the game 
pygame.init()

#how big do we want the game screen??
square_size=100
width=Cols*square_size
height=Rows+1*square_size
size=(width,height)
rad=int(square_size/2-7)

screen=pygame.display.set_mode(size)

In [1]:
def place_piece(board, row, col, piece):
	board[row][col] = piece

def valid_loc(board, col):
	return board[Rows-1][col] == 0


In [59]:
def draw_pygameBoard(board):
    #building the background
    for col in range(Cols):
        for row in range(Rows):
            pygame.draw.rect(screen,Blue,(col*square_size,row*square_size+square_size,square_size,square_size))#creating a base rectangle
            pygame.draw.circle(screen,Black,(int(col*square_size+square_size/2),int(row*square_size+square_size+square_size/2)),rad)#creating the little circles to enclose the pieces
    
    for col in range(Cols):
        for row in range(Rows):
            if board[row][col]==1:
                pygame.draw.circle(screen,Red,(int(col*square_size+square_size/2),height-int(row*square_size+square_size/2)),rad)
            elif board[row][col]==2:
                pygame.draw.circle(screen,Green,(int(col*square_size+square_size/2),height-int(row*square_size+square_size/2)),rad)
    pygame.display.update()

In [60]:
board=create_board()
print(board)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [61]:
def place_piece(board,row,col,piece):
    board[row][col]=piece

In [62]:
def valid_loc(board,col):
    return board[Rows-1][col]==0

In [63]:
def get_nextRow(board,col):
    #Checks which row will piece fall in
    for row in range(Rows):
        if board[row][col]==0:
            return row  #still empty
        

In [64]:
def flip_board(board):
    print(np.flip(board,0))#flipping along x axis

In [65]:
def who_won(board,piece):
    #Horizontal check
    for col in range(Cols-3):
        for row in range(Rows):
            if board[row][col]==piece and board[row][col+1]==piece and board[row][col+2]==piece and board[row][col+3]==piece:
                return True
            
    #Vertical check
    for col in range(Cols):
        for row in range(Rows-3):
            if board[row][col]==piece and board[row+1][col]==piece and board[row+2][col]==piece and board[row+3][col]==piece:
                return True
    
    #Diagonals toward the top
    for col in range(Cols-3):
        for row in range(Rows-3):
            if board[row][col]==piece and board[row+1][col+1]==piece and board[row+2][col+2]==piece and board[row+3][col+3]==piece:
                return True
    
    #Diagonals toward the bottom
    for col in range(Cols-3):
        for row in range(3,Rows):
            if board[row][col]==piece and board[row-1][col+1]==piece and board[row-2][col+2]==piece and board[row-3][col+3]==piece:
                return True
    
    
    

In [66]:
#Main Game loop

game_is_over=False;
turn=0
while not game_is_over:
    for event in pygame.event.get():
        if event.type==pygame.QUIT:
            sys.exit()
        
        if event.type==pygame.MOUSEMOTION:
            pygame.draw.rect(screen,Black,(0,0,width,square_size))
            posx=event.pos[0]
            if turn==0:
                pygame.draw.circle(screen,Red,(posx,int(square_size/2)),rad)
            else:
                pygame.draw.circle(screen,Green,(posx,int(square_size/2)),rad)
        pygame.display.update()
        
        if event.type==pygame.MOUSEBUTTONDOWN:
            pygame.draw.rect(screen,Black,(0,0,width,square_size))
            #print(event.pos)
            if turn==0:
                posx=event.pos[0]
                
                column_selection=int(math.floor(posx/square_size))#int(input("Player 1 , your turn. Choose an integer from (0-6)"))
        #       print("Player 1's selection is : ",selection)
                if valid_loc(board,column_selection):
                    row = get_nextRow(board,column_selection)
                    place_piece(board,row,column_selection,1)

                if who_won(board,1):
                    label=fonts.render("Player 1 wins!",1,Red)
                    pygame.display.update()
                    game_is_over=True


        #     Player 2 input
            else:
                posx=event.pos[0]
                column_selection=int(math.floor(posx/square_size))
                #         print("Player 2's selection is : ",selection)
                if valid_loc(board,column_selection):
                    row = get_nextRow(board,column_selection)
                    place_piece(board,row,column_selection,2)


                if who_won(board,2):
                    label=fonts.render("Player 2 wins!",2,Green)
                    pygame.display.update()
                    game_is_over=True



            flip_board(board)
            draw_pygameBoard(board) 
            turn+=1
            turn=turn%2#to alternate between player 1 and player 2
            
            if game_is_over:
                pyame.time.wait(7000)
           
        

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 2. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 2. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 2. 2. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 2. 2. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [2. 1. 1. 0. 2. 2. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [2. 1. 1.

SystemExit: 

C:\Users\Parth Rangarajan\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3339: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [53]:
'''
r=int(input("Enter the number of rows in game : "))
c=int(input("Enter the number of columns in game : "))
def create_board():
    board=np.zeros((r,c))
    return board
# A matrix of zeroes

b=create_board()
print(b)
'''

Enter the number of rows in game :  8
Enter the number of columns in game :  9


[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
